app/urls.py
from django.conf.urls import patterns, url
from app import views

urlpatterns = patterns('',
	url(r'^index/$', views.index, name="create_thread"),
	url(r'^thread/(?P<thread_id>\w+)/$', views.thread, name="view thread"),
	url(r'^numposts/(?P<thread_id>\w+)/$', views.numberofposts, name="numberofposts"),
	url(r'^report_thread/(?P<thread_id>\w+)/$', views.report_thread, name="report_thread"),
	url(r'^report_post/(?P<post_id>\w+)/$', views.report_post, name="report_post"),
	url(r'^post/(?P<post_id>\w+)/$', views.post_redirect, name="post_redirect")
)

backpage/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'backpage.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^app/', include('app.urls'))
)

app/models.py
from django.db import models

class Thread(models.Model):
	title = models.CharField(max_length=200)
	thread_pos = models.IntegerField(default=1)
	text = models.TextField(default='')
	time = models.DateTimeField(auto_now_add=True, null=True)
	last_post_time = models.DateTimeField(auto_now_add=True, null=True)
	reports = models.IntegerField(default = 0)
	post_count = models.IntegerField(default = 0)
	poster = models.GenericIPAddressField(null=True)
	admin = models.BooleanField(default = False)

	
	def __str__(self):
		return self.title

class Post(models.Model):
	time_posted = models.DateTimeField(auto_now_add=True)
	text = models.TextField(default='')
	reports = models.IntegerField(default = 0)
	thread = models.ForeignKey('Thread', related_name='posts')
	poster = models.GenericIPAddressField(null=True)
	admin = models.BooleanField(default = False)


	def __str__(self):
		return self.text

class ThreadReport(models.Model):
	thread = models.ForeignKey('Thread')
	message = models.CharField(max_length = 500, default = '')

	def __str__(self):
		return self.message

class PostReport(models.Model):
	post = models.ForeignKey('Post')
	message = models.CharField(max_length = 500, default = '')

	def __str__(self):
		return self.message

app/forms.py
from django import forms
from app.models import Thread, Post, ThreadReport, PostReport

class ThreadForm(forms.ModelForm):
	title = forms.CharField(widget = forms.TextInput(attrs={
		'placeholder': 'Your title here'
		}), max_length = 200)
	text = forms.CharField(widget = forms.Textarea(attrs={
		'placeholder':'Enter your text here...'
		}), max_length = 4962)

	class Meta:
		model = Thread
		fields = ['title', 'text']

class PostForm(forms.ModelForm):
	text = forms.CharField(widget = forms.Textarea, max_length = 4962)

	class Meta:
		model = Post
		fields = ['text']

class PostReportForm(forms.ModelForm):
	message = forms.CharField(max_length = 500)

	class Meta:
		model = PostReport
		fields = ['message']

class ThreadReportForm(forms.ModelForm):
	message = forms.CharField(max_length = 500)
	class Meta:
		model = ThreadReport
		fields = ['message']

app/views.py
from django.shortcuts import render
from app.forms import ThreadForm, PostForm, PostReportForm, ThreadReportForm
from app.models import Thread, Post, ThreadReport, PostReport
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse

def threads_in_order():
	return sorted(Thread.objects.all(), key=lambda x: x.last_post_time, reverse=True)

def threads_in_rev_order():
	return sorted(Thread.objects.all(), key=lambda x: x.last_post_time)

def index(request):
	''' A view for the index page. We list all the current threads here and
		also give the user the ability to create new threads here. '''
	context_dict = {'form': ThreadForm()}
	max_number = 20
	if request.method == 'POST':
		thread_form = ThreadForm(request.POST)
		if thread_form.is_valid():
			thread = thread_form.save(commit=False)
			thread.poster = request.META['REMOTE_ADDR']
			if Thread.objects.count() > max_number:
				threads = threads_in_rev_order()
				a = threads[0]
				a.delete()
				posts = Post.objects.filter(thread = a)
				for p in posts:
					p.delete()
			thread.save()
			return HttpResponseRedirect("/app/thread/"+str(thread.id)+"/")
		else:
			print(thread_form.errors)
	context_dict['all_threads'] = threads_in_order()
	return render(request, 'app/index.html', context_dict)

def thread(request, thread_id):
	''' A view for rendering the threads '''
	thread_id = int(thread_id)
	try:
		current_thread = Thread.objects.get(id=thread_id)
	except Thread.DoesNotExist:
		return HttpResponse("404 Thread does not exist")
	context_dict = {
		'thread': current_thread,
		'thread_report_form': ThreadReportForm(),
		'post_report_form': PostReportForm()
	}
	if request.method == 'POST':
		post_form = PostForm(request.POST)
		if post_form.is_valid():
			post = post_form.save(commit = False)
			post.thread = current_thread
			post.poster = request.META['REMOTE_ADDR']
			post.save()
			current_thread.last_post_time = post.time_posted
			current_thread.post_count += 1
			current_thread.save()
			print(str(current_thread.last_post_time))
		else:
			print(post_form.errors)
	context_dict['post_form'] = PostForm()
	context_dict['posts'] = Post.objects.filter(thread = current_thread)
	context_dict['num_posts'] = len(context_dict['posts'])
	return render(request, 'app/thread.html', context_dict)

def numberofposts(request, thread_id):
	''' This view returns the posts in the thread in the form of JSON.
		It exists because eventually we might use Ajax to make requests to this
		view for autorefresh of threads. '''
	thread_id = int(thread_id)
	try:
		current_thread = Thread.objects.get(id=thread_id)
	except Thread.DoesNotExist:
		return HttpResponse("404 Thread does not exist")
	posts = Post.objects.filter(thread = current_thread)
	dict_posts = {}
	for i in posts:
		dict_posts[i.id] = {'text':i.text, 'time': i.time_posted}

	return JsonResponse(dict_posts)

def report_thread(request, thread_id):
	''' A view for the reporting of threads. '''
	thread_id = int(thread_id)
	context_dict = {'form': ThreadReportForm(), 'current_thread': thread_id}
	try:
		current_thread = Thread.objects.get(pk=thread_id)
	except Thread.DoesNotExist:
		return HttpResponse("404 The thread you are trying to report does not exist")
	if request.method == 'POST':
		thread_report_form = ThreadReportForm(request.POST)
		if thread_report_form.is_valid():
			thread_report = thread_report_form.save(commit=False)
			thread_report.thread = current_thread
			thread_report.save()
			current_thread.reports=ThreadReport.objects.filter(thread=current_thread).count()
			current_thread.save()
			return HttpResponseRedirect("/app/thread/"+str(current_thread.id)+"/")
		else:
			print(thread_report_form.errors)
	return render(request, 'app/thread_report.html', context_dict)

def report_post(request, post_id):
	''' A view for the reporting of posts. '''
	post_id = int(post_id)
	context_dict = {'form': PostReportForm(),'post_id': post_id}
	try:
		current_post = Post.objects.get(pk=post_id)
	except Post.DoesNotExist:
		return HttpResponse("404 The post you're trying to report does not exist")
	if request.method == 'POST':
		post_report_form = PostReportForm(request.POST)
		if post_report_form.is_valid():
			post_report = post_report_form.save(commit = False)
			post_report.post = current_post
			post_report.save()
			current_post.reports = PostReport.objects.filter(post = current_post).count()
			current_post.save()
			thread_id = current_post.thread.id
			return HttpResponseRedirect("/app/thread/"+str(thread_id)+"/")
		else:
			print(post_report_form.errors)
	return render(request, 'app/post_report.html', context_dict)

def post_redirect(request, post_id):
	''' A view for redirecting "/app/post/<post_id>" urls to appropriate threads.'''
	post_id = int(post_id)
	try:
		current_post = Post.objects.get(pk=post_id)
		thread = current_post.thread
		id = thread.id
		try:
			Thread.objects.get(pk=id)
		except Thread.DoesNotExist:
			return HttpResponse("404 Does Not Exist")
		return HttpResponseRedirect("/app/thread/"+str(id)+"/#divPost"+str(post_id))
	except Post.DoesNotExist:
		return HttpResponse("404 The post you're trying to open does not exist")

templates/app/all_threads.html
<!doctype html>
<head>
	<title>All threads</title>
</head>

<body>
	<ul>
	{%for i in threads%}
		<li><a href="/app/thread/{{i.id}}">{{i.title}}</a></li>
	{% endfor %}
	</ul>
</body>

templates/app/create_thread.html
<!DOCTYPE html>
<html>
	<head>
		<title>Create a thread</title>
	</head>
	<body>
		<form action="/app/create/" method="post">
			{% csrf_token %}
			{{form}}
			<input type="submit" name="submit" value="create thread" />
		</form>
	</body>
</html>

templates/app/index.html
<!doctype html>
<!-- Test comment please ignore. -->
{% load staticfiles %}
<head>
	<link rel="icon" type="image/icon" href="{% static 'images/toucan1.png'%}">
<title>BackPage</title>
<script src="{% static 'js/scroll.js' %}"></script>
<style>
@font-face {
	font-family: opificio;
	src: url("{% static 'fonts/Opificio.ttf'%}");
}
*{
	padding: 0px;
	margin: 0px;
}
body {
	min-width: 980px;
	overflow: hidden;
}
#divslide1, #divslide2, #divslide3,#divslide4{
	width: 100%;
	height: 100%;
	position: absolute;
}
#divslide1{
	background-color: #6e6496;
	top: 0%;
}
#divslide2{
	background-color: #59a6a6;
	top: 100%;
}
#divslide3{
	background-color: #3333CC;
	top: 100%;
}
#divslide4 {
	background-color: 	#FF7575;
	top: 100%;
}
#divnav{
	float: left;
	position: fixed;
	top: 45%;
	left: 3%;
	z-index: 1500;
}
#divnav1,#divnav2,#divnav3,#divnav4{
	width: 15px;
	height: 15px;
	border-radius: 10px;
	background-color: white;
	z-index: 1500;
	margin-top: -20px;
	position: fixed;
}
#divnav1:hover,#divnav2:hover,#divnav3:hover,#divnav4:hover{
	box-shadow: 0px 0px 2px 2px white;
	background-color: brown;
}

#divform {
	width: 30%;
	height: 25%;
	position: absolute;
	left: 35%;
	top: 32%;
	text-align: center;
	font-family: verdana;
}
#id_title{
	margin-top: 11%;
	display: inline-block;
	width: 90%;
	height: 35px;
	padding-left: 5px;
	padding: 10px;
	font-size: 25px;
	border: none;
	border-radius: 5px;
}
#id_text{
	width: 90%;
	height: 70px;
	margin-top: 10px;
	padding-left: 5px;
	padding: 10px;
	font-size: 15px;
	border: none;
	border-radius: 5px;
}
#submitbutton {
	width: 95%;
	height: 40px;
	margin-top: 10px;
	border: none;
	padding: 5px;
	font-size: 25px;
	border-radius: 5px;
	font-family: opificio;
	background-color: #59a6a6;
	color: white;
	text-shadow: 0px 0px 1px black;
}
#submitbutton:hover {
	background-color: #1B3232;
	text-shadow: 0px 0px 1px black;
	box-shadow: 0px 0px 1px 1px white inset;
}
#id_text:focus,#id_title:focus {
	box-shadow: none;
	border: none;
}
#divover {
	width: 100%;
	height: 100%;
	overflow: hidden;
	background-color: black;
	opacity: 0.5;
	position: fixed;
	top: 0%;
	left: 0%;
	z-index: 2000;
}
#spanabout{
	font-family: opificio;
	font-size: 100px;
	color: #ffffcc;
	position: absolute;
	left: 20%;
	top: 20%;
	text-shadow: 0px 0px 3px black;
	font-weight: bold;
}
#spancontent {
	font-size: 42px;
	position: absolute;
	font-family: opificio;
	left: 20%;
	top: 37%;
	color: white;
}
#divheader{
	width: 100%;
	height: 6%;
	position: absolute;
	z-index: 10000;
	top: 0px;
	left: 0px;
	box-shadow: 0px 0px 1px 1px black;
	background-color: rgba(51,51,204,0.6);
	color: white;
	line-height: 300%;
}
#spanheaderhome {
	font-family: impact;
	margin-left: 50px;
	font-size: 30px;
}
#spanheaderhome:hover{
	text-decoration: underline;
}
#spanheaderabout {
	font-family: impact;
	margin-left: 50px;
	font-size: 30px;
}
#spanheaderabout:hover{
	text-decoration: underline;
}
#spanheadercreate{
	font-family: impact;
	margin-left: 50px;
	font-size: 30px;
}
#spanheadercreate:hover{
	text-decoration: underline;
}
#spanheaderthread {
	font-family: impact;
	margin-left: 50px;
	font-size: 30px;
}
#spanheaderthread:hover{
	text-decoration: underline;
}
.divthread {
	width: 16%;
	height: 20%;
	border: 1px solid black;
	float: left;
	margin-left: 2%;
	margin-top: 2%;
	overflow: hidden;
	text-align: center;
}
#divcontainer {
	margin-left: 15%;
	margin-top: 5%;
	height: 90%;
}
.divthreaddetails{
	width: 100%;
	height: 0;
	background-color: rgba(100,110,100,0.7);
	position: relative;
	z-index: 1200;
	overflow: hidden;
	text-align: center;
	line-height: 100px;
}

.divthreaddetails {
	-webkit-transition: height 1s;
	-moz-transition: height 1s;
	transition: height 1s;
	-ms-transition: height 1s;
}
.divthread:hover .divthreaddetails{
	height: 100%;
}
.span1, .span2{
	-webkit-transition: visibility 1s;
	-moz-transition: visibility 1s;
	transition: visibility 1s;
	-ms-transition: visibility 1s;
}
.divthread:hover .span1 , .divthread:hover .span2{
	visibility: hidden;
}
</style>

</head>
<body>


<div id="divnav">
<div id="divnav1" onClick="functionscroll1()"></div><br>
<div id="divnav2" onClick="functionscroll2()"></div><br>
<div id="divnav3" onClick="functionscroll3()"></div><br>
<div id="divnav4" onClick="functionscroll4()"></div>
</div>

<div id="divslide1">
	<img src="{% static 'images/toucanfinal2.png'%}" id="mascot" style="position: absolute; right: 0%; top: 20%;">
</div>
<div id="divslide2">
<span id="spanabout">Express yourself.</span>
<span id="spancontent">We made it really easy to post anything while remaining completely anonymous the entire time. <br/> You can crib about anyone you want without them knowing it's you.</span>
</div>
<div id="divslide3">
<div id="divform">
	<form action="/app/index/" method="POST">
	{% csrf_token %}
	{{form.title}}<br>
	{{form.text}}
	<input type="submit" value="CREATE THREAD" id="submitbutton">
	</div>
</div>
<div id="divslide4">
	<div id="divcontainer">
		{%for thread in all_threads%}
		<div class="divthread" onClick="window.location.href='/app/thread/{{thread.id}}';">
		<div class="divthreaddetails">Replies: {{ thread.post_count }}</div>
			<span class="span1">{{thread.title}}</span> <br>
			<span class="span2">{{thread.text}}</span>

		</div>
		{% endfor %}
</div>
 </div>
<div id="divheader"><span id="spanheaderhome" onclick="functionscroll1()">Home</span><span id="spanheaderabout"  onclick="functionscroll2()">About Us</span><span id="spanheadercreate"  onclick="functionscroll3()">Create Thread</span><span id="spanheaderthread"  onclick="functionscroll4()">Threads</span></div>

templates/app/post_report.html
<!DOCTYPE html>
<head>
	<title>Report post</title>
</head>

<body>
	<form action="/app/report_post/{{post_id}}/" method="POST">
		{% csrf_token %}
		{{form.message}}
		<input type="submit" value="Report Post">
	</form>
</body>

templates/app/test.html
<!doctype html>
<head>
	<script src="/static/jquery-2.1.1.min.js"></script>
	<script>
		var xmlhttp = new XMLHttpRequest();
		xmlhttp.open("GET","/app/numposts/9/",true);
		xmlhttp.send();
		xmlhttp.onreadystatechange = function (){
			if(xmlhttp.readyState == 4 && xmlhttp.status == 200){
				var b = JSON.parse(xmlhttp.responseText);
				console.log(b.161.text);
			}
		}
		
	</script>
</head>
<body>
	<div id="test">
	fuck you
	</div>
</body>

templates/app/thread.html
<!DOCTYPE html>
<html>
	{% load staticfiles %}
	<head>
		<title>Thread-{{thread.id}}</title>
		<style>
		@font-face {
				font-family: print;
				src: url("{% static 'fonts/print.ttf'%}");
			}
			* {
				padding: 0px;
				margin: px;
			}
			body {
				padding: 30px;
				background-image: url("{% static 'images/back3.png' %}");
				background-size: 100vw 100vh;
				background-repeat: no-repeat;
				background-attachment: fixed;
			}
			#divThread {
				border: 1px solid black;
				width: 500px;
				border-radius: 10px;
				text-align: center;
				padding: 10px;
				margin: auto;
				margin-bottom: 10px;
				background-color: rgba(254,254,220,0.7);
			}
			.threadTitle {
				text-decoration: underline;
				display: block;
				font-size: 20px;
				font-family: verdana, arial;
			}
			.threadText {
				font-size: 18px;
				display: block;
			}
			.threadTime{
				font-size: 12px;
			}

			.divPost{
				background-color: rgba(254,254,220,0.8);
				padding: 3px 10px;
				width: 500px;
				margin: auto;
				margin-top: 10px;
				border-radius: 10px;
				border: 1px solid black;
				font-family: sans-serif;
			}
			.postNo {
				display: block;
				font-size: 15px;
				text-decoration: underline;
				margin-bottom: 10px;
			}
			.postText{
				display: block;
				font-size: 18px;
				font-family: garamond ;
			}
			.postTime{
				display: block;
				font-size: 12px;
				margin-top: 7px;
			}

			#id_text {
				width: 300px;
				height: 25px;
				padding: 2px 10px;
				margin-left: 50px;
				margin-top: 15px;
			}
			#id_submit {
				height: 33px;
				text-align: center;
				line-height: 25px;
				width: 100px;
				border: 1px solid gray;
				font-size: 15px;
				color: white;
				background-color: #6600FF;
				border-radius: 2px;
				margin-left: 10px;
			}
			#id_submit:hover {
				background-color: #80B2FF;
				color: black;
				box-shadow: 0px 0px 1px 1px gray;
			}
			#id_submit:hover {
				border: 1px solid black;
			}
			#id_submit:focus{
				border-color: blue;
			}
			#divformend {
				width: 490px;
				margin: auto;
			}
			.spanreport {
				position: relative;
				left: 450px;
				display: inline;
			}
			.spanreport1 {
				position: relative;
				left: 220px;
				display: inline;
			}
			.divpostback {
				width: 500px;
				background-color: white;
				opacity: 0.4;
			}
		</style>
		
	</head>
	<body>
		<div id="divThread">
		<span class="spanreport1" onClick="funcreportthread()">Report</span>
		<div id="reportthread"  style="position: absolute; margin-left: -15%; display: none; top: 350px; width: 300px; height: 100px; background-color: violet; border: 1px solid black; line-height: 100px; text-align: center; box-shadow: 10px 10px 2px 2px silver; border-radius: 5px; z-index: 2;">
				<form action="/app/report_thread/{{thread.id}}/" method="post">
			{% csrf_token %}
			{{thread_report_form.message}}
			<input type = "submit" value="Report Thread">
		</form>
				</div>
			<script>
				function funcreportthread(){
					document.getElementById("reportthread").style.display="inline";
				}
			</script>
		<span class="threadTitle">{{thread.title}}</span>
		<span class="threadText">{{thread.text}}</span>
		<span class="threadTime" id="threadtime">
			<script>
			var thread_time = new Date("{{thread.time|date:'Y/m/d H:i:s'}}");
			var current=new Date();
			var c=current-thread_time;
			// if difference is less than 1 minute
			if(c<60000) document.getElementById("threadtime").innerHTML="Just Now";
			// if difference is less than 2 minutes and difference is
			else if(c>60000 && c<120000) document.getElementById("threadtime").innerHTML="1 min ago";
			else if(c>120000 && (c/3600000)<1) document.getElementById("threadtime").innerHTML=Math.round(c/60000)+" mins ago";
			else if(c/3600000>1 && c/3600000<1.5) document.getElementById("threadtime").innerHTML=Math.round(c/3600000)+" Hour Ago";
			else if(c/3600000>1.5 && c/86400000<1) document.getElementById("threadtime").innerHTML=Math.round(c/3600000)+" Hours Ago";
			else if(c/86400000>1) document.getElementById("threadtime").innerHTML="{{thread.time}}";
		</script>
		</span>
			
		</div>

		{% for i in posts %}
			<div class="divPost" id="divPost{{i.id}}">
				<span class="spanreport" onClick="funcreport{{i.id}}()">Report</span>
				<div id="report{{i.id}}"  style="position: absolute; margin: auto; display: none; top: 350px; width: 300px; height: 100px; background-color: violet; border: 1px solid black; line-height: 100px; text-align: center; box-shadow: 10px 10px 2px 2px silver; border-radius: 5px;">
				<form action="/app/report_post/{{i.id}}/" method="post">
					{% csrf_token %}
					{{post_report_form.message}}
					<input type = "submit" value = "Report Post #{{i.id}}">
				</form>	
				</div>
			<script>
				function funcreport{{i.id}}(){
					document.getElementById("report{{i.id}}").style.display="inline";
				}
			</script>
			<span class="postNo"><a href="/app/thread/{{thread.id}}/#divPost{{i.id}}">Post #{{i.id}}</a></span>
			<span class="postText">{{i.text}}</span>
			{{i.poster}}
			<span class="postTime" id="post{{i.id}}"><script>
			var a = new Date("{{i.time_posted|date:'Y/m/d H:i:s'}}");
			var b=new Date();
			var c=b-a;
			// if difference is less than 1 minute
			if(c<60000) document.getElementById("post{{i.id}}").innerHTML="Just Now";
			// if difference is less than 2 minutes and difference is
			else if(c>60000 && c<12000) document.getElementById("post{{i.id}}").innerHTML="1 min ago";
			else if(c>12000 && (c/3600000)<1) document.getElementById("post{{i.id}}").innerHTML=Math.round(c/60000)+" mins ago";
			else if(c/3600000>1 && c/3600000<1.5) document.getElementById("post{{i.id}}").innerHTML="1 Hour Ago";
			else if(c/3600000>1.5 && c/86400000<1) document.getElementById("post{{i.id}}").innerHTML=Math.round(c/3600000)+" Hours Ago";
			else if(c/86400000>1) document.getElementById("post{{i.id}}").innerHTML="{{thread.time}}";
		</script></span>	
		
		
		</div>
		{% endfor %}
		<div id="divformend">

		<form action="/app/thread/{{thread.id}}/" method="post">
			{% csrf_token %}
			{{post_form.text}}
			<input type="submit" name="submit" value="Add Post" id="id_submit" />
		</form>
	</div>
	</body>
</html>

templates/app/thread_report.html
<!DOCTYPE html>
<head>
	<title>Report thread</title>
</head>

<body>
	<form action="/app/report_thread/{{current_thread}}/" method="POST">
		{% csrf_token %}
		{{form.message}}
		<input type="submit" value="Report Thread">
	</form>
</body>